### ISSUE TITLE
DLL support?

### ISSUE THREAD

**Issue by mittorn** [MartinNowak/cv2pdb#1]
It seems that MinGW-generated DLLs does not have .debug section and uses other way to store debug data

**Comment by dscho** [comment]
If you are referring to `mingw-w64`, then that is not true. The easiest way to get started with mingw-w64 is to download [MSYS2](https://msys2.github.io/) and install the base development tools: `pacman -Sy base-devel`.

Then, you *must not* forget to compile with `-g`. Otherwise there will indeed be no `.debug` section. Example:

```sh
gcc -g -o example.exe example.c
```

**Comment by mittorn** [comment]
Already found that it works. I compiled dlls with both -g and -s options before, but -s strips debug data
